/**
 * @file File type constants — MIME types, categories, extensions, icons, colors, previews, navigation, and sort options.
 */

/** Map of file extension to MIME type. */
export const MIME_TYPES = {
  // Images
  avif: 'image/avif',
  bmp: 'image/bmp',
  gif: 'image/gif',
  ico: 'image/x-icon',
  jpeg: 'image/jpeg',
  jpg: 'image/jpeg',
  png: 'image/png',
  svg: 'image/svg+xml',
  tiff: 'image/tiff',
  tif: 'image/tiff',
  webp: 'image/webp',
  // Video
  avi: 'video/x-msvideo',
  mkv: 'video/x-matroska',
  mov: 'video/quicktime',
  mp4: 'video/mp4',
  mpeg: 'video/mpeg',
  mpg: 'video/mpeg',
  webm: 'video/webm',
  wmv: 'video/x-ms-wmv',
  // Audio
  aac: 'audio/aac',
  flac: 'audio/flac',
  m4a: 'audio/mp4',
  mid: 'audio/midi',
  midi: 'audio/midi',
  mp3: 'audio/mpeg',
  ogg: 'audio/ogg',
  opus: 'audio/opus',
  wav: 'audio/wav',
  wma: 'audio/x-ms-wma',
  // Documents
  csv: 'text/csv',
  doc: 'application/msword',
  docx: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  epub: 'application/epub+zip',
  json: 'application/json',
  md: 'text/markdown',
  ods: 'application/vnd.oasis.opendocument.spreadsheet',
  odt: 'application/vnd.oasis.opendocument.text',
  pdf: 'application/pdf',
  ppt: 'application/vnd.ms-powerpoint',
  pptx: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
  rtf: 'application/rtf',
  txt: 'text/plain',
  xls: 'application/vnd.ms-excel',
  xlsx: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  xml: 'application/xml',
  // Archives
  7z: 'application/x-7z-compressed',
  bz2: 'application/x-bzip2',
  gz: 'application/gzip',
  rar: 'application/vnd.rar',
  tar: 'application/x-tar',
  tgz: 'application/gzip',
  xz: 'application/x-xz',
  zip: 'application/zip',
  // Code
  c: 'text/x-c',
  cpp: 'text/x-c++',
  cs: 'text/x-csharp',
  css: 'text/css',
  go: 'text/x-go',
  html: 'text/html',
  ini: 'text/plain',
  java: 'text/x-java',
  js: 'text/javascript',
  jsx: 'text/javascript',
  ts: 'text/typescript',
  tsx: 'text/typescript',
  json: 'application/json',
  kt: 'text/x-kotlin',
  less: 'text/less',
  php: 'text/x-php',
  py: 'text/x-python',
  rb: 'text/x-ruby',
  rs: 'text/x-rust',
  sass: 'text/x-sass',
  scss: 'text/x-scss',
  sh: 'application/x-sh',
  sql: 'application/sql',
  swift: 'text/x-swift',
  vue: 'text/html',
  yaml: 'text/yaml',
  yml: 'text/yaml',
  // Other
  torrent: 'application/x-bittorrent',
  wasm: 'application/wasm',
  crx: 'application/x-chrome-extension',
  xpi: 'application/x-xpinstall',
};

/** Map of file extension to its human-readable category. */
export const FILE_CATEGORIES = /** @type {const} */ ({
  image: 'image',
  video: 'video',
  audio: 'audio',
  document: 'document',
  archive: 'archive',
  code: 'code',
  other: 'other',
});

/** File extensions grouped by category. */
export const FILE_EXTENSIONS = {
  image: ['avif', 'bmp', 'gif', 'ico', 'jpeg', 'jpg', 'png', 'svg', 'tiff', 'tif', 'webp'],
  video: ['avi', 'mkv', 'mov', 'mp4', 'mpeg', 'mpg', 'webm', 'wmv'],
  audio: ['aac', 'flac', 'm4a', 'mid', 'midi', 'mp3', 'ogg', 'opus', 'wav', 'wma'],
  document: ['csv', 'doc', 'docx', 'epub', 'json', 'md', 'ods', 'odt', 'pdf', 'ppt', 'pptx', 'rtf', 'txt', 'xls', 'xlsx', 'xml'],
  archive: ['7z', 'bz2', 'gz', 'rar', 'tar', 'tgz', 'xz', 'zip'],
  code: ['c', 'cpp', 'cs', 'css', 'go', 'html', 'ini', 'java', 'js', 'jsx', 'kt', 'less', 'php', 'py', 'rb', 'rs', 'sass', 'scss', 'sh', 'sql', 'swift', 'ts', 'tsx', 'vue', 'yaml', 'yml'],
};

/**
 * Map of file extension to icon name (referencing icons.js exports).
 * @type {Record<string, string>}
 */
export const FILE_ICONS = {
  // Images
  avif: 'image',
  bmp: 'image',
  gif: 'image',
  ico: 'image',
  jpeg: 'image',
  jpg: 'image',
  png: 'image',
  svg: 'image',
  tiff: 'image',
  tif: 'image',
  webp: 'image',
  // Video
  avi: 'video',
  mkv: 'video',
  mov: 'video',
  mp4: 'video',
  mpeg: 'video',
  mpg: 'video',
  webm: 'video',
  wmv: 'video',
  // Audio
  aac: 'music',
  flac: 'music',
  m4a: 'music',
  mid: 'music',
  midi: 'music',
  mp3: 'music',
  ogg: 'music',
  opus: 'music',
  wav: 'music',
  wma: 'music',
  // Documents
  csv: 'fileSpreadsheet',
  doc: 'fileText',
  docx: 'fileText',
  epub: 'fileText',
  json: 'fileCode',
  md: 'fileText',
  ods: 'fileSpreadsheet',
  odt: 'fileText',
  pdf: 'fileText',
  ppt: 'filePresentation',
  pptx: 'filePresentation',
  rtf: 'fileText',
  txt: 'fileText',
  xls: 'fileSpreadsheet',
  xlsx: 'fileSpreadsheet',
  xml: 'fileCode',
  // Archives
  '7z': 'archive',
  bz2: 'archive',
  gz: 'archive',
  rar: 'archive',
  tar: 'archive',
  tgz: 'archive',
  xz: 'archive',
  zip: 'zip',
  // Code
  c: 'fileCode',
  cpp: 'fileCode',
  cs: 'fileCode',
  css: 'fileCode',
  go: 'fileCode',
  html: 'fileCode',
  ini: 'fileCode',
  java: 'fileCode',
  js: 'fileCode',
  jsx: 'fileCode',
  kt: 'fileCode',
  less: 'fileCode',
  php: 'fileCode',
  py: 'fileCode',
  rb: 'fileCode',
  rs: 'fileCode',
  sass: 'fileCode',
  scss: 'fileCode',
  sh: 'terminal',
  sql: 'db',
  swift: 'fileCode',
  ts: 'fileCode',
  tsx: 'fileCode',
  vue: 'fileCode',
  yaml: 'fileCode',
  yml: 'fileCode',
};

/**
 * Accent colour per file extension (hex).
 * @type {Record<string, string>}
 */
export const FILE_COLORS = {
  // Images
  avif: '#E91E63',
  bmp: '#9C27B0',
  gif: '#673AB7',
  ico: '#3F51B5',
  jpeg: '#2196F3',
  jpg: '#2196F3',
  png: '#03A9F4',
  svg: '#00BCD4',
  tiff: '#009688',
  tif: '#009688',
  webp: '#4CAF50',
  // Video
  avi: '#FF5722',
  mkv: '#795548',
  mov: '#607D8B',
  mp4: '#E91E63',
  mpeg: '#9C27B0',
  mpg: '#9C27B0',
  webm: '#673AB7',
  wmv: '#3F51B5',
  // Audio
  aac: '#FF9800',
  flac: '#FF5722',
  m4a: '#795548',
  mid: '#607D8B',
  midi: '#607D8B',
  mp3: '#E91E63',
  ogg: '#9C27B0',
  opus: '#673AB7',
  wav: '#3F51B5',
  wma: '#2196F3',
  // Documents
  csv: '#4CAF50',
  doc: '#2196F3',
  docx: '#2196F3',
  epub: '#009688',
  json: '#607D8B',
  md: '#9E9E9E',
  ods: '#4CAF50',
  odt: '#2196F3',
  pdf: '#F44336',
  ppt: '#FF5722',
  pptx: '#FF5722',
  rtf: '#607D8B',
  txt: '#9E9E9E',
  xls: '#4CAF50',
  xlsx: '#4CAF50',
  xml: '#FF9800',
  // Archives
  '7z': '#795548',
  bz2: '#795548',
  gz: '#795548',
  rar: '#795548',
  tar: '#795548',
  tgz: '#795548',
  xz: '#795548',
  zip: '#795548',
  // Code
  c: '#2196F3',
  cpp: '#2196F3',
  cs: '#9C27B0',
  css: '#00BCD4',
  go: '#00BCD4',
  html: '#FF5722',
  ini: '#9E9E9E',
  java: '#FF9800',
  js: '#FFC107',
  jsx: '#00BCD4',
  kt: '#FF9800',
  less: '#00BCD4',
  php: '#673AB7',
  py: '#2196F3',
  rb: '#F44336',
  rs: '#FF9800',
  sass: '#E91E63',
  scss: '#E91E63',
  sh: '#4CAF50',
  sql: '#FF9800',
  swift: '#F44336',
  ts: '#2196F3',
  tsx: '#2196F3',
  vue: '#4CAF50',
  yaml: '#607D8B',
  yml: '#607D8B',
};

/**
 * Preview handler type per extension.
 * @type {Record<string, string>}
 */
export const FILE_PREVIEW = {
  avif: 'gallery',
  bmp: 'gallery',
  gif: 'gallery',
  ico: 'gallery',
  jpeg: 'gallery',
  jpg: 'gallery',
  png: 'gallery',
  svg: 'gallery',
  tiff: 'gallery',
  tif: 'gallery',
  webp: 'gallery',
  avi: 'player',
  mkv: 'player',
  mov: 'player',
  mp4: 'player',
  mpeg: 'player',
  mpg: 'player',
  webm: 'player',
  wmv: 'player',
  aac: 'player',
  flac: 'player',
  m4a: 'player',
  mp3: 'player',
  ogg: 'player',
  opus: 'player',
  wav: 'player',
  wma: 'player',
  pdf: 'viewer',
  txt: 'viewer',
  md: 'viewer',
  json: 'viewer',
  xml: 'viewer',
  html: 'viewer',
  css: 'viewer',
  js: 'viewer',
  ts: 'viewer',
};

const NAV_ICONS = {
  home: 'home',
  recent: 'clock',
  favorites: 'star',
  trash: 'trash',
  images: 'image',
  videos: 'video',
  music: 'music',
  documents: 'fileText',
  archives: 'archive',
  shared: 'share',
  settings: 'settings',
};

/**
 * Sidebar navigation item definitions.
 * @type {Array<{ id: string, label: string, icon: string, path: string, category?: string }>}
 */
export const NAV_ITEMS = [
  { id: 'home', label: 'My Drive', icon: NAV_ICONS.home, path: '/' },
  { id: 'recent', label: 'Recent', icon: NAV_ICONS.recent, path: '/recent' },
  { id: 'favorites', label: 'Favorites', icon: NAV_ICONS.favorites, path: '/favorites' },
  { id: 'images', label: 'Images', icon: NAV_ICONS.images, path: '/category/image', category: 'image' },
  { id: 'videos', label: 'Videos', icon: NAV_ICONS.videos, path: '/category/video', category: 'video' },
  { id: 'music', label: 'Music', icon: NAV_ICONS.music, path: '/category/audio', category: 'audio' },
  { id: 'documents', label: 'Documents', icon: NAV_ICONS.documents, path: '/category/document', category: 'document' },
  { id: 'archives', label: 'Archives', icon: NAV_ICONS.archives, path: '/category/archive', category: 'archive' },
  { id: 'shared', label: 'Shared', icon: NAV_ICONS.shared, path: '/shared' },
  { id: 'trash', label: 'Trash', icon: NAV_ICONS.trash, path: '/trash' },
  { id: 'settings', label: 'Settings', icon: NAV_ICONS.settings, path: '/settings' },
];

/** Sort option definitions for file listing. */
export const SORT_OPTIONS = [
  { id: 'name', label: 'Name', field: 'name', ascending: true },
  { id: 'size', label: 'Size', field: 'size', ascending: false },
  { id: 'date', label: 'Date modified', field: 'updatedAt', ascending: false },
  { id: 'type', label: 'Type', field: 'mimeType', ascending: true },
];
